project_id = "nxlylxjiagleoasnzlsk"

[functions.bunny-config]
verify_jwt = false

[functions.bunny-status]
verify_jwt = false

[functions.bunny-list]
verify_jwt = false

[functions.upload-verify]
verify_jwt = false

[functions.bunny-upload]
verify_jwt = false

[functions.bunny-delete]
verify_jwt = false
