/**
 * Vinys v2.1 — Condition profiles.
 * Maps legacy ConditionKey → ConditionIdV2 and defines per-condition safety rules.
 */

import type { ConditionProfileV2, ConditionIdV2 } from "./types";
import type { ConditionKey } from "@/constants/conditions";

// ═══════════════════════════════════
// LEGACY CONDITION KEY MAPPING
// ═══════════════════════════════════

export const LEGACY_CONDITION_MAP: Record<ConditionKey, ConditionIdV2> = {
  back_pain: "back_pain",
  neck_pain: "neck_shoulder",
  shoulder_pain: "neck_shoulder",
  knee_pain: "knees",
  hip_pain: "hips_pelvis",
  pregnancy: "pregnancy",
  postpartum: "postpartum",
  fibromyalgia: "fibromyalgia",
  disc_herniation: "sciatica",
  sciatica: "sciatica",
  osteoarthritis: "osteoarthritis",
  post_injury_rehab: "back_pain",
  stress_anxiety: "stress_sleep",
  sleep_issues: "stress_sleep",
  menopause: "menopause",
  older_adult: "osteoarthritis",
  cross_training: "back_pain",
  general_yoga: "back_pain",
  weight_management: "back_pain",
  // ── New conditions → engine profile mappings ──
  scoliosis: "scoliosis",
  hypermobility: "hypermobility",
  burnout: "stress_sleep",
  nervous_system_dysregulation: "stress_sleep",
  trauma_recovery: "trauma_recovery",
  perimenopause: "perimenopause",
  hormonal_fatigue: "hormonal_fatigue",
  thyroid_conditions: "stress_sleep",
  chronic_fatigue_syndrome: "fibromyalgia",
  long_covid: "long_covid",
  low_energy: "fibromyalgia",
  post_illness: "post_illness",
  postural_fatigue: "back_pain",
  desk_tension: "neck_shoulder",
  breathing_disorders: "stress_sleep",
  core_instability: "back_pain",
  repetitive_strain: "neck_shoulder",
  // ── New area-based conditions ──
  ankle_pain: "knees",
  upper_back_pain: "neck_shoulder",
  wrist_pain: "neck_shoulder",
  // ── Clinical modifier conditions ──
  osteoporosis: "osteoporosis",
  dysautonomia_pots: "long_covid",
  endometriosis: "hormonal_fatigue",
};

// ═══════════════════════════════════
// CONDITION PROFILES
// ═══════════════════════════════════

export const CONDITION_PROFILES: Record<ConditionIdV2, ConditionProfileV2> = {
  back_pain: {
    id: "back_pain",
    relevanceKey: "backPain",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Focus on core stability and spinal mobility. Avoid loaded flexion if acute.",
  },
  neck_shoulder: {
    id: "neck_shoulder",
    relevanceKey: "neckShoulder",
    requiredTags: ["shoulderSafe"],
    excludedPoseSets: [],
    contraRules: { avoidOverhead: true },
    notes: "Prioritize gentle neck mobility and shoulder release. Avoid overhead loading.",
  },
  hips_pelvis: {
    id: "hips_pelvis",
    relevanceKey: "hipsPelvis",
    requiredTags: ["kneeSafe"],
    excludedPoseSets: [],
    contraRules: { avoidDeepKneeFlexion: true },
    notes: "Focus on hip mobility and pelvic stability.",
  },
  knees: {
    id: "knees",
    relevanceKey: "knees",
    requiredTags: ["kneeSafe"],
    excludedPoseSets: [],
    contraRules: { avoidDeepKneeFlexion: true },
    notes: "Strengthen muscles around knee, avoid deep loaded flexion.",
  },
  pregnancy: {
    id: "pregnancy",
    relevanceKey: "pregnancy",
    requiredTags: ["pregnancySafe"],
    excludedPoseSets: ["prone"],
    contraRules: { avoidSupineLong: true },
    notes: "Prenatal-safe only. Stage-specific rules applied at runtime.",
  },
  fibromyalgia: {
    id: "fibromyalgia",
    relevanceKey: "fibromyalgia",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Gentle, low-intensity, nervous system calming. Avoid overexertion.",
  },
  sciatica: {
    id: "sciatica",
    relevanceKey: "sciatica",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: { avoidFlexion: true, avoidRotation: true },
    notes: "Protect nerve path. No deep flexion or rotation under load.",
  },
  osteoarthritis: {
    id: "osteoarthritis",
    relevanceKey: "osteoarthritis",
    requiredTags: ["oaSafe"],
    excludedPoseSets: [],
    contraRules: { avoidDeepKneeFlexion: true },
    notes: "Joint-friendly movement. Avoid high-impact and deep flexion.",
  },
  stress_sleep: {
    id: "stress_sleep",
    relevanceKey: "stressSleep",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Calming breath, gentle movement, extended relaxation.",
  },
  hypermobility: {
    id: "hypermobility",
    relevanceKey: "hipsPelvis",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: { avoidEndRangeStretching: true },
    notes: "Focus on stability over flexibility. Cap release scores. Avoid end-range stretching.",
    stabilityBias: true,
    releaseCap: 2,
  },
  postpartum: {
    id: "postpartum",
    relevanceKey: "pregnancy",
    requiredTags: ["pregnancySafe"],
    excludedPoseSets: [],
    contraRules: { avoidHighAbdominalLoad: true },
    notes: "Gradual postnatal recovery. Avoid high abdominal load exercises.",
  },
  long_covid: {
    id: "long_covid",
    relevanceKey: "fibromyalgia",
    requiredTags: ["universalSafe", "flareSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Ultra-gentle recovery. Penalize standing, favor supine. Use fibro scores as base.",
    standingScorePenalty: -2,
    supineScoreBonus: 1,
  },
  menopause: {
    id: "menopause",
    relevanceKey: "stressSleep",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Hormonal transition support. Bone-loading bonus for standing stability exercises.",
    boneLoadingBonus: 2,
  },
  perimenopause: {
    id: "perimenopause",
    relevanceKey: "stressSleep",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Early hormonal transition. Amplified energy-aware scoring.",
    energyAmplifier: 1.3,
  },
  hormonal_fatigue: {
    id: "hormonal_fatigue",
    relevanceKey: "stressSleep",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Hormonal fatigue support. Cap breath hold exercises at score 2.",
    breathScoreOverrides: {
      breath_box: 2,
      breath_478: 2,
    },
  },
  trauma_recovery: {
    id: "trauma_recovery",
    relevanceKey: "stressSleep",
    requiredTags: ["universalSafe"],
    excludedPoseSets: ["prone"],
    contraRules: {},
    notes: "Trauma-informed practice. Exclude prone. Offer choice cues.",
    offerChoiceCues: true,
  },
  scoliosis: {
    id: "scoliosis",
    relevanceKey: "backPain",
    requiredTags: ["universalSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Scoliosis support. Asymmetric cueing for spinal alignment.",
    asymmetricCueing: true,
  },
  post_illness: {
    id: "post_illness",
    relevanceKey: "fibromyalgia",
    requiredTags: ["universalSafe", "flareSafe"],
    excludedPoseSets: [],
    contraRules: {},
    notes: "Post-illness deconditioning. Gentle standing penalty.",
    standingScorePenalty: -1,
  },
  osteoporosis: {
    id: "osteoporosis",
    relevanceKey: "backPain",
    requiredTags: ["universalSafe"],
    excludedPoseSets: ["highImpact"],
    contraRules: { avoidSpinalFlexion: true, avoidHighImpact: true },
    notes: "Bone fragility. Exclude high-impact and spinal flexion. Prioritise weight-bearing for bone density.",
    boneLoadingBonus: 2,
  },
};
